In [1]:
!pip install numpy

In [3]:
import numpy as np

Random Module

In [4]:
np.random.seed(42)


*   Uniform Random Numbers

* Normally distributed numbers
* Random Integers
* Random Choice
* Random Shuffle

In [20]:
arr=np.random.rand(3,4)
arr

array([[0.01563641, 0.42340148, 0.39488152, 0.29348817],
       [0.01407982, 0.1988424 , 0.71134195, 0.79017554],
       [0.60595997, 0.92630088, 0.65107703, 0.91495968]])

In [6]:
np.random.randn(3,4)

array([[-0.46947439,  0.54256004, -0.46341769, -0.46572975],
       [ 0.24196227, -1.91328024, -1.72491783, -0.56228753],
       [-1.01283112,  0.31424733, -0.90802408, -1.4123037 ]])

In [7]:
np.random.randint(0,10,(3,3))

array([[2, 6, 3],
       [8, 2, 4],
       [2, 6, 4]])

In [11]:
np.random.choice([1,2,3],5)

array([1, 2, 1, 2, 3])

In [21]:
np.random.shuffle(arr)

In [22]:
arr

array([[0.60595997, 0.92630088, 0.65107703, 0.91495968],
       [0.01407982, 0.1988424 , 0.71134195, 0.79017554],
       [0.01563641, 0.42340148, 0.39488152, 0.29348817]])

In [23]:
shuffled_arr=np.random.permutation(arr)

In [24]:
shuffled_arr

array([[0.01563641, 0.42340148, 0.39488152, 0.29348817],
       [0.60595997, 0.92630088, 0.65107703, 0.91495968],
       [0.01407982, 0.1988424 , 0.71134195, 0.79017554]])

In [25]:
#array[index]
arr=np.array([10,20,30,40,50])

In [26]:
arr[2]

np.int64(30)

In [27]:
arr[-1]

np.int64(50)

In [28]:
nd_arr=np.array([
    [10,20,30],
    [40,50,60]
])

In [29]:
#array[row, column]
nd_arr[1,2]

np.int64(60)

In [30]:
arr[[0,2,4]]

array([10, 30, 50])

In [32]:
my_list=[1,2,3,4]
my_list=my_list *2
my_list

[1, 2, 3, 4, 1, 2, 3, 4]

In [31]:
arr=arr *2
arr

array([ 20,  40,  60,  80, 100])

In [33]:
arr[arr > 25]

array([ 40,  60,  80, 100])

In [35]:
#np.where(condition,x - Value to replace if true,y - Value to replace if false)

arr=np.array([1,5,8,10])
np.where(arr >= 5)

(array([1, 2, 3]),)

In [36]:
np.where(arr>=5,20,0)

array([ 0, 20, 20, 20])

In [39]:
arr[::2]

array([1, 8])

In [40]:
arr[-4:-1]

array([1, 5, 8])

In [41]:
arr[::-1]

array([10,  8,  5,  1])

In [50]:
nd_arr=np.array([
    [10,20],
    [40,50],
    [1,2]
])

In [51]:
nd_arr[1,1:]

array([50])

In [52]:
nd_arr.reshape((2,3))

array([[10, 20, 40],
       [50,  1,  2]])

# NumPy Challenge 1 – Student Scores

A teacher has the following student scores:

```python
[55, 72, 81, 64, 90, 47, 88, 95, 60, 73]
```

Using NumPy:

1. Create a NumPy array from the list.
2. Print the following array information:
   - Shape
   - Number of dimensions
   - Size
   - Data type
3. Print:
   - The first score
   - The last score
   - The middle four scores using slicing
4. Print only the scores greater than or equal to **70** using boolean indexing.
5. Replace all scores below **60** with **60** using `np.where()`.
6. Reshape the final array into a **(2,5)** matrix.

# NumPy Challenge 2 – Matrix Explorer

Create the following matrix **without typing the numbers manually**:

```text
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
```

Using NumPy only:

1. Print the second row.
2. Print the fourth column.
3. Print the first two rows.
4. Print the last three columns.
5. Print the center **2×3** submatrix.
6. Print the four corner elements using fancy indexing.
7. Reverse the order of the rows.
8. Flatten the matrix.
9. Reshape it into a **(5,4)** matrix.

# NumPy Challenge 3 – Random Data Investigation

Create a **4×5** matrix of random integers between **10** and **99**.

Without using loops:

1. Print the matrix.
2. Print:
   - Shape
   - Size
   - Number of dimensions
3. Print the first row.
4. Print the last column.
5. Print all values greater than **50**.
6. Replace every value less than **30** with **0** using `np.where()`.
7. Convert the matrix into a one-dimensional array.
8. Restore it back to its original shape.

In [ ]:
#hi i am ahmed

# NumPy Challenge 5 – NumPy Escape Room

Without manually typing the numbers, create the following matrix:

```text
[[10 20 30 40]
 [50 60 70 80]
 [90 100 110 120]]
```

Complete the following tasks:

1. Print the array information:
   - Shape
   - Size
   - Number of dimensions
   - Data type
   - Item size
   - Total memory usage
2. Extract:
   - First row
   - Last row
   - First column
   - Last column
   - The middle two columns
3. Print only the values greater than **60**.
4. Replace every value greater than **90** with **999** using `np.where()`.
5. Reverse the entire matrix.
6. Reshape it into **(2,6)**.
7. Flatten it into a one-dimensional array.
8. Convert it into a column vector of shape **(12,1)**.
9. Create a new array containing only the elements at indices **[0, 3, 5, 8, 11]** using fancy indexing.
10. Print the final array's shape.