In [2]:
import numpy as np


Random module

In [3]:
np.random.seed(42)


uniform random numbers
normally distributed number
random integers
random choice
random shuffle

In [4]:
np.random.rand(3,4)

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848],
       [0.15601864, 0.15599452, 0.05808361, 0.86617615],
       [0.60111501, 0.70807258, 0.02058449, 0.96990985]])

In [5]:
np.random.randn(3,4)

array([[-0.46947439,  0.54256004, -0.46341769, -0.46572975],
       [ 0.24196227, -1.91328024, -1.72491783, -0.56228753],
       [-1.01283112,  0.31424733, -0.90802408, -1.4123037 ]])

In [7]:
np.random.randint(0,10,(3,3))

array([[2, 6, 3],
       [8, 2, 4],
       [2, 6, 4]], dtype=int32)

In [9]:
np.random.choice([1,2,3,4,5,6,7],5)

array([7, 2, 4, 1, 4])

In [24]:
arr=np.array([1,2,3,4,5,6,7])
nd_arr=np.array([[1,2,3],[4,5,6]])

In [13]:
nd_arr[1,2]

np.int64(6)

In [21]:
arr_1=nd_arr*2
arr_1
arr[arr>2]
np.where(arr>5,4,6)

array([[6, 6, 4],
       [4, 4, 4]])

In [22]:
arr=[1,2,3,4,5,6,7]

In [23]:
arr[::-1]

[7, 6, 5, 4, 3, 2, 1]

In [49]:
nd_arr[1,1:]

array([5, 6])

In [29]:
arr=np.array([55,72,81,64,90,47,88,95,60,73])

In [42]:
arr.shape
arr.ndim
arr.size
arr.dtype

dtype('int64')

In [36]:
print(arr[0])
print(arr[-1])
print(arr[3:7])

55
73
[64 90 47 88]


In [41]:
arr[arr>=70]
np.where(arr<60,60,arr)
arr.reshape(2,5)

array([[55, 72, 81, 64, 90],
       [47, 88, 95, 60, 73]])

In [53]:
arr=np.array(range(1,21,1))
arr=arr.reshape(4,5)


In [64]:
print("second row",arr[1,:])
print(arr[:,3])
print(arr[0:2,:])
print(arr[:,1:4])
print(arr[1:3,1:4])



second row [ 6  7  8  9 10]
[ 4  9 14 19]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 2  3  4]
 [ 7  8  9]
 [12 13 14]
 [17 18 19]]
[[ 7  8  9]
 [12 13 14]]


In [70]:
arr=np.random.randint(0,99,(4,5))
print("the matrix",arr)
print("shape",arr.shape)
print("size",arr.size)
print("number of dimentions",arr.ndim)
print("firist row",arr[0,:])
print("last column",arr[:,4])
print("values greater than 50",arr[arr>50])
print("values less than 30",np.where(arr<30,0,arr))
print("to one dimentional array",arr.reshape(1,20))
print("original shape",arr.reshape(4,5))

the matrix [[62 10 80  7 34]
 [34 32  4 40 27]
 [ 6 72 71 11 33]
 [32 47 22 61 87]]
shape (4, 5)
size 20
number of dimentions 2
firist row [62 10 80  7 34]
last column [34 27 33 87]
values greater than 50 [62 80 72 71 61 87]
values less than 30 [[62  0 80  0 34]
 [34 32  0 40  0]
 [ 0 72 71  0 33]
 [32 47  0 61 87]]
to one dimentional array [[62 10 80  7 34 34 32  4 40 27  6 72 71 11 33 32 47 22 61 87]]
original shape [[62 10 80  7 34]
 [34 32  4 40 27]
 [ 6 72 71 11 33]
 [32 47 22 61 87]]


In [75]:
arr=np.array(range(10,121,10))
print("array\n",arr)
print("shape\n",arr.shape)
print("size\n",arr.size)
print("n of dimentions\n",arr.ndim)
print("data type",arr.dtype)
print("greater than 60\n",arr[arr>60])
print("replace greater than 90 with 999",np.where(arr>90,999,arr))
print(arr.flatten())
arr=arr.flatten()
print(arr[[1,2,3]])


array
 [ 10  20  30  40  50  60  70  80  90 100 110 120]
shape
 (12,)
size
 12
n of dimentions
 1
data type int64
greater than 60
 [ 70  80  90 100 110 120]
replace greater than 90 with 999 [ 10  20  30  40  50  60  70  80  90 999 999 999]
[ 10  20  30  40  50  60  70  80  90 100 110 120]
[20 30 40]


In [77]:
import pandas as pd


ModuleNotFoundError: No module named 'pandas'

In [1]:
    import matplotlib.pyplot as plt
    import seaborn as sns
    

ModuleNotFoundError: No module named 'matplotlib'